// <auto-generated />
namespace BayMaxShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DroptablesWishlistPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DroptablesWishlistPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202312201039075_Drop-tables-Wishlist-Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
